### ISSUE TITLE
Empty dist_dir

### ISSUE THREAD

**Issue by perlpunk** [yanick/Dancer2-Plugin-Showterm#2]
Hi,
I just installed Dancer2::Plugin::Showterm 0.0.1, but it seems there are no files in the share directory:
```
% perl -MFile::ShareDir=dist_dir -E'say dist_dir("Dancer2-Plugin-Showterm")'
/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/x86_64-linux/auto/Dancer2/Plugin/Showterm
% ls -a /perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/x86_64-linux/auto/Dancer2/Plugin/Showterm
.  ..  .packlist
```

**Comment by yanick** [comment]
ooops. I'll push the fix this week-end.

**Comment by perlpunk** [comment]
Thanks! (Meanwhile I used the files from Dancer::Plugin::Showterm)

While you're at it, the regex for the path doesn't look right, and I had to fix it to make it work:
https://github.com/yanick/Dancer2-Plugin-Showterm/blob/master/lib/Dancer2/Plugin/Showterm.pm#L129-L132

```
regexp => qr/.*\.showterm\//,
vs.
s/\.showterm$/\.typescript/;
```

**Comment by yanick** [comment]
Done and sent toward CPAN. Danke schön!
